name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # You can adjust this if needed

      - name: Install dependencies
        run: bun install

      - name: Build the site
        run: bun run build

      - name: Disable Jekyll (add .nojekyll)
        run: touch ./dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Ensure you're deploying the correct folder
